# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 47d6d3ec9cd1f0326068567c039d56337a6d30f69167f62c090bbed2d6e4359b1253eaf8b3a70d5ac2a5e7325d2323f0fd34053050b9e7bc68d3d7c065528bc9

test:
  secret_key_base: c3daec8016575eee69282001477a4e9f7e14623b32a61507b9d6dccfc79963bd406338aa8bbe6cb369afc4d69caaf6873b9be505855ddd452c29bbb482d018a7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
